# Generated by Django 5.2 on 2025-05-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eas_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='cron_expression',
            field=models.CharField(blank=True, help_text="Cron expression, required if frequency is 'cron'", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='frequency',
            field=models.CharField(choices=[('once', 'Once'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('cron', 'Cron')], help_text='Schedule frequency', max_length=50),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='next_run_at',
            field=models.DateTimeField(db_index=True, help_text="Time for the next execution. Required if frequency is 'once'."),
        ),
    ]
